import type { SearchSpec } from "./types.ts";

export const SEARCHES: SearchSpec[] = [
  {
    id: "dallas-hotels",
    region: "Texas",
    places: "Dallas, Texas",
    focus:
      "the hotel development pipeline: new hotels, announced hotel projects, hotels under construction, and hotel renovations or conversions",
    depth: "heavy",
    location: { country: "US", region: "Texas", city: "Dallas" },
  },
  {
    id: "dallas-dining-nightlife",
    region: "Texas",
    places: "Dallas, Texas",
    focus: "restaurants, bars, and nightclubs that are planned, under construction, or opening soon",
    depth: "heavy",
    location: { country: "US", region: "Texas", city: "Dallas" },
  },
  {
    id: "fort-worth",
    region: "Texas",
    places: "Fort Worth, Texas",
    focus: "hotels, restaurants, bars, and nightclubs that are planned, under construction, renovating, converting, or opening soon",
    depth: "standard",
    location: { country: "US", region: "Texas", city: "Fort Worth" },
  },
  {
    id: "north-dfw-suburbs",
    region: "Texas",
    places: "Frisco, Plano, McKinney, and The Colony, Texas",
    focus: "hotels, restaurants, bars, and nightclubs that are planned, under construction, renovating, converting, or opening soon",
    depth: "standard",
    location: { country: "US", region: "Texas", city: "Frisco" },
  },
  {
    id: "mid-cities",
    region: "Texas",
    places: "Irving, Las Colinas, Grapevine, Arlington, and Addison, Texas",
    focus: "hotels, restaurants, bars, and nightclubs that are planned, under construction, renovating, converting, or opening soon",
    depth: "standard",
    location: { country: "US", region: "Texas", city: "Irving" },
  },
  {
    id: "austin-hotels",
    region: "Texas",
    places: "Austin, Texas",
    focus:
      "the hotel development pipeline: new hotels, announced hotel projects, hotels under construction, and hotel renovations or conversions",
    depth: "heavy",
    location: { country: "US", region: "Texas", city: "Austin" },
  },
  {
    id: "austin-dining-nightlife",
    region: "Texas",
    places: "Austin, Texas",
    focus: "restaurants, bars, and nightclubs that are planned, under construction, or opening soon",
    depth: "heavy",
    location: { country: "US", region: "Texas", city: "Austin" },
  },
  {
    id: "austin-suburbs",
    region: "Texas",
    places: "Round Rock, Georgetown, and Leander, Texas",
    focus: "hotels, restaurants, bars, and nightclubs that are planned, under construction, renovating, converting, or opening soon",
    depth: "standard",
    location: { country: "US", region: "Texas", city: "Round Rock" },
  },
  {
    id: "houston-hotels",
    region: "Texas",
    places: "Houston, Texas",
    focus:
      "hotel renovations, hotel conversions, and new hotel projects, including buildings being converted into hotels",
    depth: "heavy",
    location: { country: "US", region: "Texas", city: "Houston" },
  },
  {
    id: "houston-dining-nightlife",
    region: "Texas",
    places: "Houston, Texas",
    focus: "restaurants, bars, and nightclubs that are planned, under construction, or opening soon",
    depth: "standard",
    location: { country: "US", region: "Texas", city: "Houston" },
  },
  {
    id: "houston-suburbs",
    region: "Texas",
    places: "The Woodlands, Katy, and Sugar Land, Texas",
    focus: "hotels, restaurants, bars, and nightclubs that are planned, under construction, renovating, converting, or opening soon",
    depth: "standard",
    location: { country: "US", region: "Texas", city: "The Woodlands" },
  },
  {
    id: "san-antonio-hotels",
    region: "Texas",
    places: "San Antonio, Texas",
    focus:
      "hotel renovations, hotel conversions, and new hotel projects, including buildings being converted into hotels",
    depth: "heavy",
    location: { country: "US", region: "Texas", city: "San Antonio" },
  },
  {
    id: "san-antonio-dining-nightlife",
    region: "Texas",
    places: "San Antonio, Texas",
    focus: "restaurants, bars, and nightclubs that are planned, under construction, or opening soon",
    depth: "standard",
    location: { country: "US", region: "Texas", city: "San Antonio" },
  },
  {
    id: "new-braunfels",
    region: "Texas",
    places: "New Braunfels, Texas",
    focus: "hotels, restaurants, bars, and nightclubs that are planned, under construction, renovating, converting, or opening soon",
    depth: "standard",
    location: { country: "US", region: "Texas", city: "New Braunfels" },
  },
  {
    id: "fredericksburg",
    region: "Texas",
    places: "Fredericksburg, Texas",
    focus: "hotels, resorts, restaurants, bars, and nightclubs that are planned, under construction, renovating, or opening soon",
    depth: "standard",
    location: { country: "US", region: "Texas", city: "Fredericksburg" },
  },
  {
    id: "galveston",
    region: "Texas",
    places: "Galveston, Texas",
    focus: "hotels, resorts, restaurants, bars, and nightclubs that are planned, under construction, renovating, or opening soon",
    depth: "standard",
    location: { country: "US", region: "Texas", city: "Galveston" },
  },
  {
    id: "chicago-fulton-market",
    region: "Illinois",
    places: "Fulton Market and the West Loop in Chicago, Illinois",
    focus:
      "hotels, restaurants, bars, nightclubs, and major hospitality renovations that are planned, under construction, or opening soon",
    depth: "heavy",
    location: { country: "US", region: "Illinois", city: "Chicago" },
  },
  {
    id: "chicago-river-north",
    region: "Illinois",
    places: "River North, the Gold Coast, and Streeterville in Chicago, Illinois",
    focus:
      "hotels, restaurants, bars, nightclubs, and major hospitality renovations that are planned, under construction, or opening soon",
    depth: "heavy",
    location: { country: "US", region: "Illinois", city: "Chicago" },
  },
  {
    id: "chicago-loop",
    region: "Illinois",
    places: "the Loop in Chicago, Illinois",
    focus:
      "hotels, restaurants, bars, nightclubs, and major hospitality renovations that are planned, under construction, or opening soon",
    depth: "heavy",
    location: { country: "US", region: "Illinois", city: "Chicago" },
  },
  {
    id: "chicago-wicker-logan",
    region: "Illinois",
    places: "Wicker Park and Logan Square in Chicago, Illinois",
    focus: "restaurants, bars, nightclubs, and hotels that are planned, under construction, or opening soon",
    depth: "heavy",
    location: { country: "US", region: "Illinois", city: "Chicago" },
  },
  {
    id: "chicago-citywide",
    region: "Illinois",
    places: "Chicago, Illinois",
    focus:
      "the current flow of new restaurants, bars, hotels, and major hospitality renovations, including projects reported by Choose Chicago and the business press",
    depth: "heavy",
    location: { country: "US", region: "Illinois", city: "Chicago" },
  },
  {
    id: "rosemont-ohare",
    region: "Illinois",
    places: "Rosemont and the O'Hare area, Illinois",
    focus: "hotels, restaurants, bars, and nightclubs that are planned, under construction, renovating, converting, or opening soon",
    depth: "standard",
    location: { country: "US", region: "Illinois", city: "Rosemont" },
  },
  {
    id: "oak-brook-schaumburg",
    region: "Illinois",
    places: "Oak Brook and Schaumburg, Illinois",
    focus: "hotels, restaurants, bars, and nightclubs that are planned, under construction, renovating, converting, or opening soon",
    depth: "standard",
    location: { country: "US", region: "Illinois", city: "Schaumburg" },
  },
  {
    id: "naperville-evanston",
    region: "Illinois",
    places: "Naperville and Evanston, Illinois",
    focus: "hotels, restaurants, bars, and nightclubs that are planned, under construction, renovating, converting, or opening soon",
    depth: "standard",
    location: { country: "US", region: "Illinois", city: "Naperville" },
  },
  {
    id: "nashville-hotels",
    region: "Tennessee",
    places: "Nashville, Tennessee",
    focus:
      "the hotel development pipeline: new hotels, announced hotel projects, hotels under construction, and hotel renovations or conversions",
    depth: "heavy",
    location: { country: "US", region: "Tennessee", city: "Nashville" },
  },
  {
    id: "nashville-dining-nightlife",
    region: "Tennessee",
    places: "Nashville, Tennessee",
    focus: "restaurants, bars, and nightclubs that are planned, under construction, or opening soon",
    depth: "heavy",
    location: { country: "US", region: "Tennessee", city: "Nashville" },
  },
  {
    id: "franklin-brentwood",
    region: "Tennessee",
    places: "Franklin and Brentwood, Tennessee",
    focus: "hotels, restaurants, bars, and nightclubs that are planned, under construction, renovating, converting, or opening soon",
    depth: "standard",
    location: { country: "US", region: "Tennessee", city: "Franklin" },
  },
  {
    id: "murfreesboro",
    region: "Tennessee",
    places: "Murfreesboro, Tennessee",
    focus: "hotels, restaurants, bars, and nightclubs that are planned, under construction, renovating, converting, or opening soon",
    depth: "standard",
    location: { country: "US", region: "Tennessee", city: "Murfreesboro" },
  },
  {
    id: "memphis-area",
    region: "Tennessee",
    places: "Memphis, Germantown, and Collierville, Tennessee",
    focus: "hotels, restaurants, bars, and nightclubs that are planned, under construction, renovating, converting, or opening soon",
    depth: "standard",
    location: { country: "US", region: "Tennessee", city: "Memphis" },
  },
  {
    id: "knoxville",
    region: "Tennessee",
    places: "Knoxville, Tennessee",
    focus: "hotels, restaurants, bars, and nightclubs that are planned, under construction, renovating, converting, or opening soon",
    depth: "standard",
    location: { country: "US", region: "Tennessee", city: "Knoxville" },
  },
  {
    id: "chattanooga",
    region: "Tennessee",
    places: "Chattanooga, Tennessee",
    focus: "hotels, restaurants, bars, and nightclubs that are planned, under construction, renovating, converting, or opening soon",
    depth: "standard",
    location: { country: "US", region: "Tennessee", city: "Chattanooga" },
  },
  {
    id: "smokies",
    region: "Tennessee",
    places: "Gatlinburg, Pigeon Forge, and Sevierville, Tennessee",
    focus:
      "hotels, resorts, cabin resorts, restaurants, bars, and nightlife venues that are planned, under construction, renovating, or opening soon in the Smoky Mountains",
    depth: "standard",
    location: { country: "US", region: "Tennessee", city: "Gatlinburg" },
  },
  {
    id: "san-juan",
    region: "Puerto Rico",
    places: "San Juan, Puerto Rico, including Condado, Miramar, and Old San Juan",
    focus: "hotels, resorts, restaurants, bars, and nightclubs that are planned, under construction, renovating, converting, or opening soon",
    depth: "heavy",
    location: { country: "PR", region: "San Juan", city: "San Juan" },
  },
  {
    id: "isla-verde",
    region: "Puerto Rico",
    places: "Carolina and Isla Verde, Puerto Rico",
    focus: "hotels, resorts, restaurants, bars, and nightclubs that are planned, under construction, renovating, converting, or opening soon",
    depth: "standard",
    location: { country: "PR", region: "Carolina", city: "Carolina" },
  },
  {
    id: "dorado-rio-grande",
    region: "Puerto Rico",
    places: "Dorado and Río Grande, Puerto Rico",
    focus: "hotels, resorts, restaurants, bars, and nightclubs that are planned, under construction, renovating, or opening soon",
    depth: "standard",
    location: { country: "PR", region: "Dorado", city: "Dorado" },
  },
  {
    id: "palmas-del-mar",
    region: "Puerto Rico",
    places: "Humacao and Palmas del Mar, Puerto Rico",
    focus: "hotels, resorts, restaurants, bars, and nightclubs that are planned, under construction, renovating, or opening soon",
    depth: "standard",
    location: { country: "PR", region: "Humacao", city: "Humacao" },
  },
  {
    id: "ponce",
    region: "Puerto Rico",
    places: "Ponce, Puerto Rico",
    focus: "hotels, resorts, restaurants, bars, and nightclubs that are planned, under construction, renovating, converting, or opening soon",
    depth: "standard",
    location: { country: "PR", region: "Ponce", city: "Ponce" },
  },
  {
    id: "west-coast-pr",
    region: "Puerto Rico",
    places: "Cabo Rojo, Rincón, and Aguadilla, Puerto Rico",
    focus: "hotels, resorts, restaurants, bars, and nightclubs that are planned, under construction, renovating, or opening soon",
    depth: "standard",
    location: { country: "PR", region: "Cabo Rojo", city: "Rincón" },
  },
  {
    id: "vieques-culebra",
    region: "Puerto Rico",
    places: "Vieques and Culebra, Puerto Rico",
    focus: "hotels, resorts, restaurants, bars, and nightclubs that are planned, under construction, renovating, or opening soon",
    depth: "standard",
    location: { country: "PR", region: "Vieques", city: "Vieques" },
  },
  {
    id: "roosevelt-roads",
    region: "Puerto Rico",
    places: "Ceiba and Roosevelt Roads, Puerto Rico",
    focus: "hotels, resorts, restaurants, and redevelopment projects that are planned, under construction, or opening soon",
    depth: "standard",
    location: { country: "PR", region: "Ceiba", city: "Ceiba" },
  },
  {
    id: "puerto-rico-island",
    region: "Puerto Rico",
    places: "Puerto Rico, including resort areas outside San Juan",
    focus:
      "major resort and hotel projects anywhere on the island, including government announcements and projects in Ponce, Vieques, and other resort areas",
    depth: "heavy",
    location: { country: "PR", region: "Puerto Rico", city: "San Juan" },
  },
];
